baseURL = '/'
languageCode = 'en-gb'
title = 'Codam Student Council Website'
theme = 'terminal'
copyright = '<a href="https://github.com/CodamStudentCouncil/webite">View source code</a>'

[params]
themeColor = "green"
oneHeadingSize = false

[languages]
[languages.en]
    languageName = "English"
    title = "Codam Student Council"

    [languages.en.params.logo]
        logoText = "Codam Student Council"
        logoHomeLink = "/"

    [languages.en.menu]
        [[languages.en.menu.main]]
        identifier = "timeline"
        name = "Timeline"
        url = "/timeline"

        [[languages.en.menu.main]]
        identifier = "join"
        name = "Join the Council"
        url = "/join"

        [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"
